version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - dynamodb-local
    environment:
      - APP_AWS_REGION=us-east-1
      - APP_DDB_TABLE_NAME=apprunner-demo-data
      - APP_MODE=LOCAL
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

volumes:
  db:
    driver: local
